version: "2"
services:

  redis:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

  rabbit:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"

  time_service:
    build:
      context: time_service
    depends_on:
      - rabbit
    environment:
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"

  parameter_service:
    build:
      context: parameter_service
    depends_on:
      - rabbit
    environment:
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"

volumes:
  redis-data:

